[apps.PDFMathTranslate]
product = 'PDFMathTranslate'
version = '0.1.beta'
name = 'PDFMathTranslate'
icon = './Assets/img/icon.png'


[apps.PDFMathTranslate.plist]
CFBundleShortVersionString = "$(version)"